server:
  port: 8080
spring:
  application:
    name: "franquicias"
  devtools:
    add-properties: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

adapters:
  r2dbc:
    host: pragma.c9yymogiek8f.us-east-2.rds.amazonaws.com
    port: 5432
    database: aws
    schema: public
    username: postgres
    password: Veguita97

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
